name: pokex
description: "PokeX"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  http: ^1.3.0
  provider: ^6.1.2
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_ce_generator: ^1.8.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/home.png
    - assets/icons/heart.png
    - assets/icons/heart-full.png
    - assets/icons/settings.png

    - assets/icons/logo.png

    - .env


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/logo.png"
  windows:
    generate: true
    image_path: "assets/icons/logo.png"
  macos:
    generate: true
    image_path: "assets/icons/logo.png"