// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:pokex/model/pokemon.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AbilityAdapter());
    registerAdapter(PokemonAdapter());
    registerAdapter(PokemonSpeciesAdapter());
    registerAdapter(TypeEntryAdapter());
    registerAdapter(TypeInfoAdapter());
  }
}
